In [1]:
import pandas as pd # use for data analysis
import numpy as np # used to perform varity of opertaion on array
import seaborn as sns # used for datat visualization
import matplotlib.pyplot as plt # uused for creating ststic ,animated and interactive visualization


In [3]:
df=pd.read_csv('emails.csv')

In [4]:
df.head(10)

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   
5   Email 6    4   5    1    4    2   3   45    1    0  ...         0    0   
6   Email 7    5   3    1    3    2   1   37    0    0  ...         0    0   
7   Email 8    0   2    2    3    1   2   21    6    0  ...         0    0   
8   Email 9    2   2    3    0    0   1   18    0    0  ...         0    0   
9  Email 10    4   4   35    0    1   0   49    1   16  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  
5       0    0               0         0         0   0    0           1  
6       0    0               0         0         0   0    0           0  
7       0    0               0         0         0   1    0           1  
8       0    0               0         0         0   0    0           0  
9       0    0               0         0         0   0    0           0  

[10 rows x 3002 columns]

In [5]:
df.info() # print full summary of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB


In [6]:
df.isnull().sum()


Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [7]:
x=df.iloc[:,1:-1].values

In [8]:
x

array([[ 0,  0,  1, ...,  0,  0,  0],
       [ 8, 13, 24, ...,  0,  1,  0],
       [ 0,  0,  1, ...,  0,  0,  0],
       ...,
       [ 0,  0,  1, ...,  0,  0,  0],
       [ 2,  7,  1, ...,  0,  1,  0],
       [22, 24,  5, ...,  0,  0,  0]], dtype=int64)

In [9]:
y=df.iloc[:,-1].values

In [10]:
y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [11]:
df.tail(10)

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
5162  Email 5163    2   3    1    2    1   2   32    0    0  ...         0   
5163  Email 5164    0   0    1    0    0   0    1    0    0  ...         0   
5164  Email 5165   21  18    3    1    6   4  106    1    2  ...         0   
5165  Email 5166    1   0    1    0    3   1   12    1    0  ...         0   
5166  Email 5167    1   0    1    1    0   0    4    0    0  ...         0   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
5162    0       0    0               0         0         0   0    0   
5163    0       0    0               0         0         0   0    0   
5164    0       0    0               0         0         0   0    0   
5165    0       0    1               0         0         0   0    0   
5166    0       0    0               0         0         0   0    0   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
5162           1  
5163           1  
5164           0  
5165           0  
5166           1  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[10 rows x 3002 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=45)

In [14]:
#split your dataset into subsets #test size indicate 30% data will be used for testing 
# random state controlls shuffling applied to the data befre applying  split

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [16]:
y_pred=classifier.predict(x_test) # predict methoud of KNeighborsclassifier class perform prediction on testing instance


In [17]:
from sklearn.metrics import confusion_matrix ,accuracy_score
cm=confusion_matrix(y_test,y_pred) #evaluate accuracy of classification


In [18]:
cm

array([[960, 156],
       [ 75, 361]], dtype=int64)

In [20]:
from sklearn.metrics import classification_report
cl_report=classification_report(y_test,y_pred)
cl_report

'              precision    recall  f1-score   support\n\n           0       0.93      0.86      0.89      1116\n           1       0.70      0.83      0.76       436\n\n    accuracy                           0.85      1552\n   macro avg       0.81      0.84      0.83      1552\nweighted avg       0.86      0.85      0.85      1552\n'

In [21]:
print("Accuracy score for KNN:",accuracy_score(y_pred,y_test))
#a ration of correctly predicated observation to the observations


Accuracy score for KNN: 0.851159793814433
